/**
 * Scans assets/tiles/<setting>/<themeCategory-or-_generic>/<floors|props>/ for image files
 * TileGenerator.mjs can scatter across a floor as decorative Tile documents. Entirely optional:
 * an empty or missing folder just means TileGenerator emits nothing for that slot - dropping
 * art in later is enough, nothing else in the pipeline needs to change or re-run by hand beyond
 * the normal generate:floors.
 *
 * Foundry serves any file under a module's own root by its module-relative path
 * ("modules/dcw-content/assets/tiles/..."), so no packing/registration step is needed beyond
 * committing the image files - unlike compendium content, these never go through classic-level.
 *
 * For the `dungeon` setting, also merges in the free DCSS 32x32 tile pack dropped at
 * assets/tiles/dungeon/ in its own native layout (floor/, altars/, statues/, traps/, water/,
 * trees/, plus a handful of loose chest/fountain/boulder/sarcophagus files) - see
 * data/tile-pack-index.json (which files, generated by generate-tile-pack-index.mjs) and
 * data/tile-pack-mapping.json (which themeCategory each file sorts into, hand-edited keyword
 * rules). The pack's files are never moved/duplicated on disk; this is purely a data-driven
 * overlay on top of its own folder layout, merged into the same pool the hand-curated scaffold
 * folders feed.
 */
import fs from 'fs';
import path from 'path';

const IMAGE_EXTENSIONS = new Set(['.webp', '.png', '.jpg', '.jpeg']);
const MODULE_ID = 'dcw-content';
const GENERIC = '_generic';
const PACK_SETTING = 'dungeon';

function listImages(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => IMAGE_EXTENSIONS.has(path.extname(f).toLowerCase()))
    .sort();
}

function readJson(file, fallback) {
  if (!fs.existsSync(file)) return fallback;
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function categoryFor(basename, rules) {
  const lower = basename.toLowerCase();
  for (const rule of rules) {
    if (lower.includes(rule.match.toLowerCase())) return rule.themeCategory;
  }
  return GENERIC;
}

/**
 * @param {string} assetsRoot - absolute path to <repo>/assets/tiles
 * @param {string} [dataRoot] - absolute path to <repo>/data (holds tile-pack-index.json /
 *   tile-pack-mapping.json); defaults to assetsRoot's sibling `data/` directory.
 * @returns {{ pool: (setting: string, themeCategory: string, kind: 'floors'|'props') => string[] }}
 */
export function loadTileLibrary(assetsRoot, dataRoot) {
  const cache = new Map();
  const resolvedDataRoot = dataRoot || path.join(assetsRoot, '..', '..', 'data');

  const packIndex = readJson(path.join(resolvedDataRoot, 'tile-pack-index.json'), []);
  const packRules = readJson(path.join(resolvedDataRoot, 'tile-pack-mapping.json'), { rules: [] }).rules;

  function pool(setting, themeCategory, kind) {
    const key = `${setting}/${themeCategory}/${kind}`;
    if (cache.has(key)) return cache.get(key);

    const toModulePath = (bucket, f) => `modules/${MODULE_ID}/assets/tiles/${setting}/${bucket}/${kind}/${f}`;
    const combined = [
      ...listImages(path.join(assetsRoot, setting, themeCategory, kind)).map(f => toModulePath(themeCategory, f)),
      ...listImages(path.join(assetsRoot, setting, GENERIC, kind)).map(f => toModulePath(GENERIC, f))
    ];

    if (setting === PACK_SETTING) {
      for (const entry of packIndex) {
        if (entry.kind !== kind) continue;
        const category = categoryFor(path.basename(entry.path), packRules);
        if (category !== themeCategory && category !== GENERIC) continue;
        combined.push(`modules/${MODULE_ID}/assets/tiles/${PACK_SETTING}/${entry.path}`);
      }
    }

    cache.set(key, combined);
    return combined;
  }

  return { pool };
}
